{{- if .Values.global.ingress.enabled -}}
{{- $labelsContext := (dict "context" . "name" "admin") -}}
{{- $fullName := include "hoppscotch.fullname" . -}}
{{- $svcPort := .Values.admin.service.containerPort -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hoppscotch.fullname" . }}-admin
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
    {{- if .Values.admin.extraLabels }}
      {{- toYaml .Values.admin.extraLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.admin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.admin.ingress }}
spec:
{{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
{{- end }}
{{- if .tls }}
  tls:
  {{- range .tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $fullName }}-admin
              port:
                number: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
