{{- $labelsContext := (dict "context" . "name" "backend") -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoppscotch.fullname" . }}-backend
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
data:
  TOKEN_SALT_COMPLEXITY: 10
  MAGIC_LINK_TOKEN_VALIDITY: 3
  REFRESH_TOKEN_VALIDITY: 604800000 # Default validity is 7 days (604800000 ms) in ms
  ACCESS_TOKEN_VALIDITY: 86400000 # Default validity is 1 day (86400000 ms) in ms
  ALLOW_SECURE_COOKIES: "true"
  REDIRECT_URL: {{ .Values.global.baseUrl | quote }}
  WHITELISTED_ORIGINS: {{ printf "%s,%s,%s" .Values.global.baseUrl (include "hoppscotch.admin.url" .) (include "hoppscotch.backend.url" .) | quote }}
  VITE_ALLOWED_AUTH_PROVIDERS: {{ .Values.global.auth.providers | quote }}
  GOOGLE_CALLBACK_URL: {{ printf "%s/v1/auth/google/callback" (include "hoppscotch.backend.url" .) | quote }}
  GOOGLE_SCOPE: "email,profile"
  GITHUB_CALLBACK_URL: {{ printf "%s/v1/auth/github/callback" (include "hoppscotch.backend.url" .) | quote }}
  GITHUB_SCOPE: "user:email"
  MICROSOFT_CALLBACK_URL: {{ printf "%s/v1/auth/microsoft/callback" (include "hoppscotch.backend.url" .) | quote }}
  MICROSOFT_SCOPE: "user.read"
  MICROSOFT_TENANT: {{ .Values.global.auth.microsoft.tenant | quote }}
  MAILER_SMTP_ENABLE: {{ .Values.global.mailer.smtpEnable | quote }}
  MAILER_USE_CUSTOM_CONFIGS: {{ .Values.global.mailer.useCustomConfigs | quote }}
  MAILER_ADDRESS_FROM: {{ .Values.global.mailer.addressFrom | quote }}
  RATE_LIMIT_TTL: "60"
  RATE_LIMIT_MAX: "100"



