{{- $labelsContext := (dict "context" . "name" "backend") -}}
{{- $databaseUrl := printf "%s-postgres.%s.svc.cluster.local:%d" (include "hoppscotch.fullname" .) .Release.Namespace (int .Values.postgres.service.port) -}}
{{- $name := printf "%s-backend" (include "hoppscotch.fullname" .) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s/%s" (include "hoppscotch.secrets.database.username" .) (include "hoppscotch.secrets.database.password" .) $databaseUrl (include "hoppscotch.secrets.database.database" .) | b64enc | quote }}
  {{- if (lookup "v1" "Secret" .Release.Namespace $name).data }}
  JWT_SECRET: {{ (lookup "v1" "Secret" .Release.Namespace $name).data.JWT_SECRET }}
  SESSION_SECRET: {{ (lookup "v1" "Secret" .Release.Namespace $name).data.SESSION_SECRET }}
  DATA_ENCRYPTION_KEY: {{ (lookup "v1" "Secret" .Release.Namespace $name).data.DATA_ENCRYPTION_KEY }}
  {{- else }}
  JWT_SECRET: {{ .Values.backend.secrets.jwt | default (randAlphaNum 24) | b64enc | quote }}
  SESSION_SECRET: {{ .Values.backend.secrets.jwt | default (randAlphaNum 24) | b64enc | quote }}
  DATA_ENCRYPTION_KEY: {{ .Values.backend.secrets.dataEncryptionKey | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  GOOGLE_CLIENT_ID: {{ .Values.global.auth.google.clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.global.auth.google.clientSecret | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.global.auth.github.clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.global.auth.github.clientSecret | b64enc | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.global.auth.microsoft.clientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.global.auth.microsoft.clientSecret | b64enc | quote }}
  MAILER_SMTP_URL: {{ .Values.global.mailer.smtpUrl | default "" | b64enc | quote }}
  MAILER_SMTP_HOST: {{ .Values.global.mailer.smtpHost | default "" | b64enc | quote }}
  MAILER_SMTP_PORT: {{ .Values.global.mailer.smtpPort | default "" | b64enc | quote }}
  MAILER_SMTP_SECURE: {{ .Values.global.mailer.smtpSecure | default "" | b64enc | quote }}
  MAILER_SMTP_USER: {{ .Values.global.mailer.smtpUser | default "" | b64enc | quote }}
  MAILER_SMTP_PASSWORD: {{ .Values.global.mailer.smtpPassword | default "" | b64enc | quote }}
  MAILER_TLS_REJECT_UNAUTHORIZED: {{ .Values.global.mailer.tlsRejectUnauthorized | default "" | b64enc | quote }}
