{{- if .Values.postgres.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hoppscotch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hoppscotch.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "hoppscotch.fullname" . }}-postgres
          image: postgres:10.1
          image: "{{ default .Values.postgres.image.repository "postgres" }}:{{ default .Values.postgres.image.tag "14.13" }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "hoppscotch.fullname" . }}-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "hoppscotch.fullname" . }}-postgres
      volumes:
        - name: {{ include "hoppscotch.fullname" . }}-postgres
          persistentVolumeClaim:
            claimName: {{ include "hoppscotch.fullname" . }}-postgres-pv-claim

{{- end -}}
