{{- if .Values.postgres.enabled -}}
{{- $labelsContext := (dict "context" . "name" "postgres") -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}-postgres
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hoppscotch.selectorLabels" $labelsContext | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hoppscotch.labels" $labelsContext | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "hoppscotch.fullname" . }}-postgres
          image: postgres:10.1
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "hoppscotch.fullname" . }}-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "hoppscotch.fullname" . }}-postgres
      volumes:
        - name: {{ include "hoppscotch.fullname" . }}-postgres
          persistentVolumeClaim:
            claimName: {{ include "hoppscotch.fullname" . }}-postgres-pv-claim

{{- end -}}
