{{- if .Values.postgres.enabled -}}

{{- $labelsContext := (dict "context" . "name" "postgres") -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.fullname" . }}-postgres
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ include "hoppscotch.secrets.database.database" . | b64enc | quote }}
  POSTGRES_USER: {{ include "hoppscotch.secrets.database.username" . | b64enc | quote }}
  POSTGRES_PASSWORD: {{ include "hoppscotch.secrets.database.password" . | b64enc | quote }}

{{- end -}}
