{{- if .Values.postgres.enabled -}}

{{- $password := or .Values.postgres.auth.password (randAlphaNum 24) -}}
{{- $user := or .Values.postgres.auth.username "postgres" -}}
{{- $database := or .Values.postgres.auth.database "postgres" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.fullname" . }}-postgres
  labels:
    {{- include "hoppscotch.labels" . | nindent 4 }}
  annotations:
    {{- include "hoppscotch.annotations" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ $database | b64enc | quote }}
  POSTGRES_USER: {{ $user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $password | b64enc | quote }}

{{- end -}}
