{{- $labelsContext := (dict "context" . "name" "frontend") -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch.fullname" . }}-frontend
  labels:
    {{- include "hoppscotch.labels" $labelsContext | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.containerPort }}
      protocol: TCP
  selector:
    {{- include "hoppscotch.selectorLabels" $labelsContext | nindent 4 }}
